apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-backend
  namespace: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: validator-backend
  template:
    metadata:
      labels:
        app: validator-backend
    spec:
      containers:
        - name: validator-backend
          image: 992122884453.dkr.ecr.eu-central-1.amazonaws.com/jumia-devops:validator-backend-50427f6b57493d814963c52694e9de911cde68cc
          resources:
            limits:
              memory: "1000Mi"
              cpu: "500m"
            requests:
              memory: "1000Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-svc
  namespace: production
spec:
  type: NodePort
  selector:
    app: validator-backend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080