apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-frontend
  namespace: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: validator-frontend
  template:
    metadata:
      labels:
        app: validator-frontend
    spec:
      containers:
        - name: validator-frontend
          image: 992122884453.dkr.ecr.eu-central-1.amazonaws.com/jumia-devops:validator-frontend
          resources:
            limits:
              memory: "1000Mi"
              cpu: "500m"
            requests:
              memory: "1000Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: validator-frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000