pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
        stage('Deploy'){
            steps {
                 sh 'kubectl apply -f deployment.yml'
            }
        }
}
